window.HTML_BODY="" 
+ "<button id='elem_id_1' name='elem_name' class='ui_element css_class ui_button' target='elem_id_1_container' callback_java_script='callback_java_script' href='/'>"
+ "elem_name"
+ "</button>"
+ "<a id='elem_id_2' name='elem_name' class='ui_element css_class ui_history_element ui_link' target='elem_id_2_container' callback_java_script='callback_java_script' href='/tab1'>"
+ "elem_name"
+ "</a>"
+ "<a id='elem_id_3' name='elem_name' class='ui_element css_class ui_history_element ui_link' target='elem_id_3_container' callback_java_script='callback_java_script' href='/tab2'>"
+ "elem_name"
+ "</a>"
+ "<a id='elem_id_4' name='elem_name' class='ui_element css_class ui_history_element ui_link' target='elem_id_4_container' callback_java_script='callback_java_script' href='/'>"
+ "elem_name"
+ "</a>" 
+ "<div id='elem_id_1_container' class='ui_container css_class'>"
+ "</div>"
+ "<div id='elem_id_2_container' class='ui_container css_class'>"
+ "</div>"
+ "<div id='elem_id_3_container' class='ui_container css_class'>"
+ "</div>"
+ "<div id='elem_id_4_container' class='ui_container css_class'>"
+ "</div>"

window.HTML_BODY_HISTORY_TEST1=""
+ "<a id='elem_id_1' class='ui_element ui_history_element ui_link' target='elem_id_1_container'  href='/tab1'>"
+ "elem_name_1"
+ "</a>"
+ "<a id='elem_id_2' class='ui_element ui_history_element ui_link' target='elem_id_1_container'  href='/tab2'>"
+ "elem_name_2"
+ "</a>"
+ "<div id='elem_id_1_container' class='ui_container css_class'>"
+ "<a id='elem_id_3' class='ui_element ui_history_element ui_link' target='elem_id_2_container'  href='/tab3'>"
+ "elem_name_3"
+ "</a>"
+ "<a id='elem_id_4' class='ui_element ui_history_element ui_link' target='elem_id_2_container'  href='/tab4'>"
+ "elem_name_4"
+ "<div id='elem_id_2_container' class='ui_container css_class'>"
+ "</div>"
+ "</a>"
+ "</div>"